name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    #- uses: jakejarvis/s3-sync-action@master
    - name: Uploading to Deployment server
      run: rsync -zhrv ./* ubuntu@3.109.48.52:/home/ubuntu/
    - run: |
       aws s3 sync . "$AWS_S3_BUCKET"
    env:
       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            

