name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
    - name: Uploading to Deployment server
      run: rsync -zhrv ./* ubuntu@3.109.48.52:/home/ubuntu/

